const categories = [
    'General Knowledge',
    'Entertainment: Books',
    'Entertainment: Film',
    'Entertainment: Music',
    'Entertainment: Musicals & Theatres',
    'Entertainment: Television',
    'Entertainment: Video Games',
    'Entertainment: Board Games',
    'Science & Nature',
    'Science: Computers',
    'Science: Mathematics',
    'Science: Gadgets',
    'Mythology',
    'Sports',
    'Geography',
    'History',
    'Politics',
    'Art',
    'Celebrities',
    'Animals',
    'Vehicles',
    'Entertainment: Comics',
    'Entertainment: Japanese Anime & Manga',
    'Entertainment: Cartoon & Animations'
]

let varCategories = {
    'General Knowledge': 0,
    'Entertainment: Books': 0,
    'Entertainment: Film': 0,
    'Entertainment: Music': 0,
    'Entertainment: Musicals & Theatres': 0,
    'Entertainment: Television': 0,
    'Entertainment: Video Games': 0,
    'Entertainment: Board Games': 0,
    'Science & Nature': 0,
    'Science: Computers': 0,
    'Science: Mathematics': 0,
    'Science: Gadgets': 0,
    'Mythology': 0,
    'Sports': 0,
    'Geography': 0,
    'History': 0,
    'Politics': 0,
    'Art': 0,
    'Celebrities': 0,
    'Animals': 0,
    'Vehicles': 0,
    'Entertainment: Comics': 0,
    'Entertainment: Japanese Anime & Manga': 0,
    'Entertainment: Cartoon & Animations': 0
}

module.exports = ('categories', categories)
module.exports = ('varCategories', varCategories)